twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_name: '%env(APP_NAME)%'
        transcription_service_host: '%env(TRANSCRIPTION_SERVICE_HOST)%'
        transcription_service_port: '%env(TRANSCRIPTION_SERVICE_PORT)%'

when@test:
    twig:
        strict_variables: true
